### ISSUE TITLE
gaussian functions not using standard form?

### ISSUE THREAD

**Issue by abonatto** [emilyripka/BlogRepo#1]
Dear Emily,

Did you square the number 2 inside the exponential function on purpose, or would this be a typo? I suppose that, in order to have the standard, normalised Gaussian, your functions should be defined as follows:

```
def _1gaussian(x, amp1, cen1, sigma1):
    return a0+amp1*(1/(sigma1*(np.sqrt(2.*np.pi))))*(np.exp(-((x-cen1)**2)/(2.*sigma1**2)))


def _2gaussian(x, amp1,cen1,sigma1, amp2,cen2,sigma2):
    return a0+amp1*(1/(sigma1*(np.sqrt(2*np.pi))))*(np.exp(-((x-cen1)**2)/(2.*sigma1**2))) +\
           amp2*(1/(sigma2*(np.sqrt(2*np.pi))))*(np.exp(-((x-cen2)**2)/(2.*sigma2**2)))
```

Cheers,

Alex

**Comment by emilyripka** [comment]
Hi Alex,

All fixed now. Sorry for the delay, have been busy wrapping up my PhD.

Thanks again for catching this. 
-Emily
